"""criando tabelas iniciais

Revision ID: 13d45833e322
Revises: 
Create Date: 2026-06-24 15:56:10.353698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13d45833e322'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Usuarios_id'), table_name='Usuarios')
    op.drop_table('Usuarios')
    op.drop_index(op.f('ix_figurinhas_id'), table_name='figurinhas')
    op.drop_table('figurinhas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('figurinhas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sigla', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('figurinhas_pkey'))
    )
    op.create_index(op.f('ix_figurinhas_id'), 'figurinhas', ['id'], unique=False)
    op.create_table('Usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Usuarios_pkey'))
    )
    op.create_index(op.f('ix_Usuarios_id'), 'Usuarios', ['id'], unique=False)
    # ### end Alembic commands ###
