"""refatora nome da tabela usuarios para minusculo

Revision ID: 46dd0a9bc5ee
Revises: ceb8cdcf3e20
Create Date: 2026-06-25 11:43:19.358374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46dd0a9bc5ee'
down_revision: Union[str, Sequence[str], None] = 'ceb8cdcf3e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_figurinhas_id'), table_name='figurinhas')
    op.drop_table('figurinhas')
    op.drop_index(op.f('ix_Usuarios_id'), table_name='Usuarios')
    op.drop_table('Usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Usuarios_pkey'))
    )
    op.create_index(op.f('ix_Usuarios_id'), 'Usuarios', ['id'], unique=False)
    op.create_table('figurinhas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sigla', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('observacao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuarios.id'], name=op.f('figurinhas_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('figurinhas_pkey'))
    )
    op.create_index(op.f('ix_figurinhas_id'), 'figurinhas', ['id'], unique=False)
    # ### end Alembic commands ###
